一，jupyter

In [3]:
import numpy as np

In [3]:
arr = np.array(5)
print(arr)
print("arr的维度：",arr.ndim)
print("数组的形状：" ,arr.shape)
print("元素的转置：",arr.T)
print("元素的个数：",arr.size)


5
arr的维度： 0
数组的形状： ()
元素的转置： 5
元素的个数： 1


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr)
print("arr的维度：",arr.ndim)
print("数组的形状：" ,arr.shape)
print("元素的转置：",arr.T)
print("元素的个数：",arr.size)

[1 2 3 4 5]
[1 2 3 4 5]
arr的维度： 1
数组的形状： (5,)
元素的转置： [1 2 3 4 5]
元素的个数： 5


In [5]:
arr = np.array([[1,2,4,5],[12,1,3,1314]])
print(arr)
print("arr的维度：",arr.ndim)
print("数组的形状：" ,arr.shape)
print("元素的转置：",arr.T)
print("元素的个数：",arr.size)

[[   1    2    4    5]
 [  12    1    3 1314]]
arr的维度： 2
数组的形状： (2, 4)
元素的转置： [[   1   12]
 [   2    1]
 [   4    3]
 [   5 1314]]
元素的个数： 8


##ndarray的创建

In [6]:
#等差数列
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [7]:
# 等间隔数列
arr = np.linspace(1,10,5)  # 开始，结束，多少份（平均）
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [8]:
#对数间隔数列
arr = np.logspace(1,4,2,base = 2)
print(arr)

[ 2. 16.]


In [ ]:
arr = np.logspace(1,4,2,base=2)


[ 2. 16.]


In [ ]:
arr = np.eye(3)   #单位矩阵
arr1 = np.diag([1,2,3])    #对角矩阵
print(arr1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
arr = np.random.rand(2,3)  #生成0,1之间的随机浮点数
arr1 = np.random.uniform(3,6,(2,3))  #生成指点范围（3,6）之间的随机浮点数  

In [ ]:
arr = np.array([1, 4, 9], dtype=int)
result = np.sqrt(arr)
print(result)
print(np.sqrt([1,4,9]).astype(int))

[1. 2. 3.]
[1 2 3]


In [ ]:
arr = np.array([1,2,3])
print(np.mean(arr))   #平均值
print(np.cumsum(arr))  #累积和
print(np.cumprod(arr))   # 累积积
print(np.median([2,8,3]))   #中位数
print(np.percentile(arr,50))  #分位数
print(np.var([1,2,3]))    #方差
print(np.std([1,2,3]))     #标准差

4.666666666666667
3.0
0.6666666666666666
0.816496580927726


比较函数

In [ ]:
print(np.greater([1,2,3,4,5,6],4))   #是否大于
print(np.less([1,2,3,4,5,6],4))     #是否小于
print(np.equal([1,2,3,4,5,6],4))     #是否等于

[False False False False  True  True]
[ True  True  True False False False]
[False False False  True False False]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(np.where(arr>3,1,2))     #三目运算符

[2 2 2 1 1 1 1]


In [25]:
score = np.random.randint(1,100,10)
print(score)
print(np.where(
    score<=60,'不及格',np.where(
        score<=80,'良好','优秀')
))

[76 90 82 31 33 17 14  5 71  3]
['良好' '优秀' '优秀' '不及格' '不及格' '不及格' '不及格' '不及格' '良好' '不及格']


In [34]:
print(np.select([score<60,(score>=60) & (score<80),(score>=80) &(score<=100)],['不及格','良好','优秀'],default='未知'))

['良好' '优秀' '优秀' '不及格' '不及格' '不及格' '不及格' '不及格' '良好' '不及格']


In [ ]:
np.random.seed(0)
arr2 = np.random.randint(1,101,10)
print(arr2)
print(np.sort(arr2))     #排序
print(np.argsort(arr2))  #数值相关索引的排序

[45 48 65 68 68 10 84 22 37 88]
[10 22 37 45 48 65 68 68 84 88]
[5 7 8 0 1 2 4 3 6 9]


In [ ]:
print(np.unique(arr))    #去重并排序

[1 2 3 4 5 6 7]


In [45]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))  #链接

[5 7 9]
[1 2 3 4 5 6]
