NumPy相关综合练习

In [1]:
import numpy as np

In [6]:
'''某城市一周的最高气温（℃）为[28，30，29，31，32，30，29]。
计算平均气温、最高气温和最低气温。
找出气温超过30℃的天数。'''
arr = np.array([28,30,29,31,32,30,29])
print("平均温度|",np.mean(arr))
print("最高温度",np.max(arr))
print("最低温度：",np.min(arr))
print("超过30度",len(arr[arr>30]))
print(np.count_nonzero(arr>30))
print(np.sum(np.where(arr>30,1,0)))

平均温度| 29.857142857142858
最高温度 32
最低温度： 28
超过30度 2
2
2


In [11]:
'''题目2：学生成绩统计
某班级5名学生的数学成绩为【85，90，78，92，88】。
计算成绩的平均分、中位数和标准差。
将成绩转换为百分制（假设满分为100）。'''

score = np.array([85,90,78,92,88])
print("平均分：",np.mean(score))
print("中位数:",np.median(score))
print("标准差：%.3f"%np.std(score))

平均分： 86.6
中位数: 88.0
标准差：4.883


In [12]:
'''题目3：矩阵运算
给定矩阵
A = [[1, 2],[3, 4]]
B = [[5, 6],[7, 8]]。
计算：
A + B（逐元素相加）
A * B（逐元素相乘）
A 与 B 的矩阵乘法（点积）'''
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(A+B)
print(A-B)
print(A*B)
print(A@B)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [33]:
'''题目4：随机数据生成
生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。
计算每列的最大值和每行的最小值。
将数组中的所有奇数替换为 -1。'''
np.random.seed(0)   #保证之后的数据不变
arr4 = np.random.randint(0,10,(3,4))
print(arr4)
for i in range(0,4):
    print(f'第{i+1}列的最大值',np.max(arr4[:,i]))
print('每列最大值：',np.max(arr4,axis = 0))

for j in range(0,3):
    print(f'每{j+1}行的最小值：',np.min(arr4[j,:]))
print('每行最小值：',np.min(arr4,axis = 1))




[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
第1列的最大值 7
第2列的最大值 9
第3列的最大值 7
第4列的最大值 6
每列最大值： [7 9 7 6]
每1行的最小值： 0
每2行的最小值： 3
每3行的最小值： 2
每行最小值： [0 3 2]


In [45]:
'''题目5：数组变形
创建一个1到12的一维数组，并转换为（3，4）的二维数组。
计算每行的和与每列的平均值。
将数组展平为一维数组。'''
arr5 = np.arange(1,13)
print(arr5)
arr = np.reshape(arr5,(3,4))
print('新数组：',arr)
print('每行的和：',np.sum(arr,axis = 1))
print('每列的值：',np.mean(arr,axis = 0))
print('展平数组',np.reshape(arr,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
新数组： [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的值： [5. 6. 7. 8.]
展平数组 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [67]:
'''题目6：布尔索引
生成一个 (5, 5) 的随机数组，范围 [0, 20)。
找出数组中大于 10 的元素。
将所有大于 10 的元素替换为 0。'''
np.random.seed(0)
arr6 = np.random.randint(0,20,(5,5))
print(arr6)
print(arr6[arr6>10])
print('替换后',np.where(arr6>10,0,arr6))


[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
替换后 [[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [79]:
'''题目7：统计函数应用
某公司6个月的销售额（万元）为[120，135，110，125，130，140]。
计算销售额的总和、均值和方差。
找出销售额最高的月份和最低的月份。'''

arr7 = np.array([120,135,110,125,130,140])
print('总和：',np.sum(arr7))
print('均值:%.2f'%np.mean(arr7))
print('方差:',np.var(arr7))
print('最高月份：',np.argmax(arr7)+1)
print('最第月份：',np.argmin(arr7)+1)


总和： 760
均值:126.67
方差: 97.22222222222223
最高月份： 6
最第月份： 3


In [83]:
'''题目8：数组拼接
给定
A = [1, 2, 3]
B = [4, 5, 6]
将 A 和 B 水平拼接为一个新数组
将 A 和 B 垂直拼接为一个新数组'''

A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate([A,B])
print('水平：',C)
print('竖直：',np.reshape(C,(2,3)))

水平： [1 2 3 4 5 6]
竖直： [[1 2 3]
 [4 5 6]]


In [90]:
'''题目9：唯一值与排序
给定数组 [2, 1, 2, 3, 1, 4, 3]。
找出数组中的唯一值并排序
计算每个唯一值出现的次数'''

arr9 = np.array([2,1,2,3,1,4,3])
arr,count= np.unique(arr9,return_counts=True)
print(arr)
print(count)


[1 2 3 4]
[2 2 2 1]


In [94]:
'''题目10：缺失值处理
给定数组 [1, np.nan, 3, np.nan, 5]。
计算数组中非缺失值的数量
将缺失值替换为 0'''

arr10 = np.array([1, np.nan, 3, np.nan, 5])
print('数量：',np.count_nonzero(~np.isnan(arr10)))
print("替换后：",np.nan_to_num(arr10,nan = 0))
print(np.where(np.isnan(arr10),0,arr10))

数量： 3
替换后： [1. 0. 3. 0. 5.]
[1. 0. 3. 0. 5.]


In [ ]:
'''题目11：三角函数计算
生成一个包含 0 到 π 的等间隔数组（共 5 个值）。
计算每个值的正弦值和余弦值，并将结果保存为一个二维数组，
第一列为正弦值，第二列为余弦值。'''
arr11 = np.linspace(0,np.pi,5)
print(arr11)

sin_num = np.sin(arr11)
cos_num = np.cos(arr11)
print(np.column_stack((sin_num,cos_num)))


[[ 0.00000000e+00  1.00000000e+00]
 [ 7.07106781e-01  7.07106781e-01]
 [ 1.00000000e+00  6.12323400e-17]
 [ 7.07106781e-01 -7.07106781e-01]
 [ 1.22464680e-16 -1.00000000e+00]]
[0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [106]:
'''题目12：数组过滤
生成一个形状为 (10,) 的随机数组，范围 [-5, 5)。
找出数组中所有正数。
计算正数的平均值。'''
np.random.seed(0)
arr12 = np.random.uniform(-5,5,10)
print(arr12)
arr = np.where(arr12>0,arr12,np.nan)
print(arr)
print(np.nanmean(arr))

[ 0.48813504  2.15189366  1.02763376  0.44883183 -0.76345201  1.45894113
 -0.62412789  3.91773001  4.63662761 -1.16558481]
[0.48813504 2.15189366 1.02763376 0.44883183        nan 1.45894113
        nan 3.91773001 4.63662761        nan]
2.018541862454357


In [109]:
'''题目13：广播机制
给定行向量 A = [1, 2, 3] 和列向量 B = [[4], [5], [6]]。
利用广播机制计算 A + B。
解释广播机制在此场景中的作用。'''

A = np.array([1, 2, 3])          # shape (3,)
B = np.array([[4], [5], [6]])    # shape (3, 1)

# 方法1：直接相加（广播自动发生）
res1 = A + B                     # shape (3, 3)
print(res1)

# 方法2：显式手工广播（等价）
A_b = np.broadcast_to(A, (3, 3)) # 把行向量复制成3行
B_b = np.broadcast_to(B, (3, 3)) # 把列向量复制成3列
res2 = A_b + B_b
print(res2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [112]:
'''题目14:分位数计算
给定数组 [10, 20, 30, 40, 50, 60, 70]。
计算下四分位数 Q1（25%）、中位数 Q2（50%）、上四分位数 Q3（75%）；
判断数据是否存在异常值（定义为超出 Q1-1.5×IQR 或 Q3+1.5×IQR）。'''
data = np.array([10, 20, 30, 40, 50, 60, 70])

# 分位数
q1, q2, q3 = np.percentile(data, [25, 50, 75])
iqr = q3 - q1

# 异常值界限
lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
outliers = data[(data < lower) | (data > upper)]

print('Q1=', q1, 'Q2=', q2, 'Q3=', q3)
print('IQR=', iqr)
print('异常值：', outliers)   # 空数组 → 本例无异常值

Q1= 25.0 Q2= 40.0 Q3= 55.0
IQR= 30.0
异常值： []


In [110]:
'''题目15：数组复制与视图
创建数组 A = [1, 2, 3]。
① 用 np.copy() 创建副本 B，修改 B[0] = 10，观察 A 是否变化；
② 用切片视图 C = A[:] 创建视图，修改 C[0] = 20，观察 A 是否变化。'''
A = np.array([1, 2, 3])

# ① 副本
B = np.copy(A)   # 或 A.copy()
B[0] = 10
print('副本修改后A:', A)   # [1 2 3]  不变

# ② 视图
C = A[:]         # 或 C = A.view()
C[0] = 20
print('视图修改后A:', A)   # [20  2  3]  跟随变化

副本修改后A: [1 2 3]
视图修改后A: [20  2  3]


In [111]:
'''题目16：对数运算
生成数组 [1, 10, 100, 1000]。
计算每个元素的自然对数（ln）和以 10 为底的对数（log10），
将结果保存为二维数组（两列或两行）。'''
# 方法1：先算后拼
ln  = np.log(arr)
log10 = np.log10(arr)
res1 = np.column_stack((ln, log10))   # 形状 (4,2)

# 方法2：一行搞定
res2 = np.vstack((np.log(arr), np.log10(arr))).T

# 方法3：np.c_[]
res3 = np.c_[np.log(arr), np.log10(arr)]

print('二维结果（ln, log10）：')
print(res1)

二维结果（ln, log10）：
[[-0.71716319 -0.31146002]
 [ 0.76634823  0.33282081]
 [ 0.02725884  0.01183836]
 [-0.801107   -0.34791635]
 [        nan         nan]
 [ 0.37771092  0.16403777]
 [        nan         nan]
 [ 1.36551241  0.5930345 ]
 [ 1.53398729  0.66620222]
 [        nan         nan]]


In [116]:
'''题目17：数组分割
给定数组 [1, 2, 3, 4, 5, 6]。
① 等分：切成 3 个子数组，每个 2 个元素；
② 不等分：得到 [1, 2], [3, 4, 5], [6]。'''
a = np.array([1,2,3,4,5,6])          # [1 2 3 4 5 6]

# ① 等分 3×2
s1 = np.split(a, 3)                     # 精确均分
s2 = np.array_split(a, 3)               # 允许不均（这里结果同 s1）
s3 = a.reshape(3, 2)                    # 转成 3 行 

# ② 指定不均分割
u1 = np.split(a, [2, 5])                # 索引切点 2,5 → [1,2],[3,4,5],[6]
u2 = [a[:2], a[2:5], a[5:]]             # 切片列表
u3 = np.array_split(a, [2, 5])          # 同样效果

print(s1)
print(s2)
print(s3)
print(u1)
print(u2)
print(u3)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[1 2]
 [3 4]
 [5 6]]
[array([1, 2]), array([3, 4, 5]), array([6])]
[array([1, 2]), array([3, 4, 5]), array([6])]
[array([1, 2]), array([3, 4, 5]), array([6])]


In [ ]:
'''题目18：矩阵转置
给定矩阵 C = [[1, 2, 3], [4, 5, 6]]。
计算转置并验证形状。'''
C = np.array([[1, 2, 3],
              [4, 5, 6]])          # shape (2, 3)

T1 = C.T                            # 属性写法
T2 = np.transpose(C)                # 函数写法
T3 = C.swapaxes(0, 1)               # 轴交换
T4 = C.reshape(3, 2)                #  reshape 也能得到同样内容（但语义不同）

print('转置后形状:', T1.shape)        # (3, 2) 符合预期

转置后形状: (3, 2)


In [ ]:
'''题目19：数组填充
创建形状 (2, 3) 的全 0 数组；
用 np.full 创建同形状全 5 数组；
用 np.fill（或切片）把全 0 数组改成全 10。'''
# 方法1：zeros → full → fill
z1 = np.zeros((2, 3), dtype=int)   # 全 0
f1 = np.full((2, 3), 5)            # 全 5
z1.fill(10)                        # 原地改全 10

# 方法2：zeros → 切片赋值
z2 = np.zeros((2, 3), dtype=int)
z2[:, :] = 10                      # 广播赋值

# 方法3：ones 乘以标量
f3 = np.ones((2, 3)) * 10          # 得到全 10

print(z1)
print(f1)

[[10 10 10]
 [10 10 10]]
[[5 5 5]
 [5 5 5]]


In [125]:
'''题目20：综合应用
某商店 5 天的销售额（万元）与成本（万元）如下：
销售额：[20, 25, 22, 30, 28]
成本：[15, 18, 16, 22, 20]
计算每天的利润（销售额 − 成本）
计算利润的平均值和标准差
找出利润最高的天数'''
A = np.array([20,25,22,30,28])
B = np.array([15,18,16,22,20])
profit = A-B
print('利润:',profit)
print('利润平均值',np.mean(profit))
print('利润标准差',np.std(profit))
print('利润最高天数',np.argmax(profit)+1)


利润: [5 7 6 8 8]
利润平均值 6.8
利润标准差 1.16619037896906
利润最高天数 4
